export const USERDETAILSWITHPOSTS = "USERDETAILSWITHPOSTS";
export const UPDATEPASSENGERDETAILS = "UPDATEPASSENGERDETAILS";
export const SETUSERDETAILSWITHPOSTS = "SETUSERDETAILSWITHPOSTS";
export const SETUPDATEPASSENGERDETAILS = "SETUPDATEPASSENGERDETAILS";
